# Example Prismatic Security Configuration
# This demonstrates all available configuration options

client:
  name: ExampleClient
  environment: production

# AWS Configuration for Prowler scanning
aws:
  profiles:
    - default
  regions:
    - us-east-1
    - us-west-2

# Docker/Container configuration for Trivy scanning
docker:
  containers:
    - nginx:latest
    - alpine:3.18
  registries:
    - docker.io

# Kubernetes configuration for Kubescape scanning
# kubernetes:
#   kubeconfig: ~/.kube/config
#   contexts:
#     - default
#   namespaces: []  # Empty means all namespaces

# Web endpoints for Nuclei scanning
endpoints:
  - https://example.com
  - https://api.example.com

# Finding suppressions
suppressions:
  global:
    date_before: "2024-01-01"  # Suppress findings before this date
  
  # Scanner-specific suppressions by finding type
  trivy:
    - "CVE-2023-12345"
  prowler:
    - "s3_bucket_public_read_access"

# Severity overrides
severity_overrides:
  "CVE-2023-12345": "low"  # Override severity for specific findings

# Business context enrichment
metadata_enrichment:
  resources:
    "arn:aws:s3:::my-bucket":
      owner: "data-team"
      data_classification: "confidential"
      business_impact: "Critical data storage"
      compliance_impact: ["GDPR", "HIPAA"]