# Example Prismatic configuration file
client:
  name: "Example Corporation"
  environment: "Development"

# AWS Configuration
aws:
  profiles:
    - default
  regions:
    - us-east-1
    - us-west-2

# Docker Configuration  
docker:
  containers:
    - nginx:latest
    - redis:alpine
    - postgres:14

# Kubernetes Configuration
kubernetes:
  contexts:
    - docker-desktop
  namespaces:
    - default
    - kube-system

# Web Endpoints to scan
endpoints:
  - https://example.com
  - https://api.example.com

# Suppressions
suppressions:
  global:
    date_before: "2023-01-01"  # Ignore findings before this date
  
  trivy:
    - CVE-2021-3711      # Old Ruby OpenSSL
    - CVE-2021-23840     # Ruby version
  
  prowler:
    - iam_user_hardware_mfa_enabled  # Using SSO instead
  
  gitleaks:
    - generic-api-key  # Too many false positives

# Severity Overrides
severity_overrides:
  CVE-2021-3711: low     # Not exploitable in our context
  check_s3_encryption: medium  # Downgrade from high

# Metadata Enrichment (optional)
metadata_enrichment:
  resources:
    "arn:aws:s3:::example-public-website":
      owner: "Marketing Team"
      data_classification: "public"
    "api-deployment":
      owner: "Platform Team"
      data_classification: "confidential"
      business_impact: "Core API service"
      compliance_impact: ["SOC2", "GDPR"]
