# Example configuration with metadata enrichment
client:
  name: example-corp
  environment: production

# AWS scanning configuration
aws:
  profiles:
    - production
  regions:
    - us-east-1
    - us-west-2

# Docker container scanning
docker:
  containers:
    - nginx:latest
    - postgres:14
    - redis:7

# Metadata enrichment - OPTIONAL
# This adds business context to findings
metadata_enrichment:
  resources:
    # S3 buckets
    "arn:aws:s3:::customer-data-bucket":
      owner: data-team
      data_classification: confidential
      business_impact: "Core customer data storage"
      compliance_impact:
        - GDPR
        - CCPA
        - SOC2
    
    "arn:aws:s3:::static-assets-bucket":
      owner: web-team
      data_classification: public
      business_impact: "Public website assets"
    
    # Docker containers
    "nginx:latest":
      owner: infrastructure-team
      data_classification: public
      business_impact: "Customer-facing web proxy"
      compliance_impact:
        - PCI-DSS
    
    "postgres:14":
      owner: data-team
      data_classification: confidential
      business_impact: "Primary application database"
      compliance_impact:
        - GDPR
        - HIPAA
        - SOC2
    
    # EC2 instances
    "i-1234567890abcdef0":
      owner: api-team
      data_classification: sensitive
      business_impact: "Payment processing service"
      compliance_impact:
        - PCI-DSS
        - SOC2

# Example suppressions
suppressions:
  trivy:
    - CVE-2021-12345  # False positive in test environment
  prowler:
    - s3_bucket_public_read  # Intentionally public buckets
  global:
    date_before: "2024-01-01"  # Suppress old vulnerabilities

# Severity overrides
severity_overrides:
  "s3_bucket_versioning": low  # Not critical in our environment